### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by seandenigris** [badetitou/Pharo-LibVLC#1]
I started looking into how to implement this. 

# Possible Approaches
Apparently, it's not so straightforward to compile libvlc on Mac, as discussed ad nauseam in [this VLC pull request GH](https://github.com/Homebrew/legacy-homebrew/pull/4234), which started with [this gist](https://gist.github.com/leehambley/2650d7b66147e1651934) and ultimately points to [this gist](https://gist.github.com/lfranchi/968230) as most up-to-date.
## Homebrew
I have VLC installed via Homebrew cask, [the formula](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/vlc.rb) for which simply installs the dmg. I first tried supplying a full path to the dylib that the VLC app uses (`/Applications/VLC.app/Contents/MacOS/lib/libvlc.5.dylib`), which resulted in `Error: External module not found`. I then remembered some trouble people have had in the past with FFI lookup locations and tried copying into the VM's plugin folder both a link and the actual dylib, with the same error. I read [the uFFI booklet](https://github.com/SquareBracketAssociates/Booklet-uFFI/releases/download/continuous/unified-ffi-wip.pdf), but didn't learn anything more.

I also checked that the VLC lib was 64-bit via:
```bash
lipo -info .../Pharo.app/Contents/MacOS/Plugins/libvlc.5.dylib 
```
which returned:
```bash
Non-fat file: .../Plugins/libvlc.5.dylib is architecture: x86_64
```

## Other
Since I'm currently starting with the Homebrew approach, I'll just briefly list other options that came up during research. There are approaches [requiring Xcode](https://github.com/tomahawk-player/homebrew-tomahawk/blob/master/vlc.rb) or [macports](https://www.tribler.org/VlcMacHowto/). The VLC seems to provide an out of the box solution only [for Windows and Linux](https://wiki.videolan.org/LibVLC_Tutorial/) and has [macOS instructions here](https://wiki.videolan.org/MacOSCompile/).

**Comment by badetitou** [comment]
Hello, 

I do not have a mac. So I did not implement the method `macLibraryName`
If I remember well, it is the first step to use FFI.
Have you implemented the method? (in VLCLibrary)

I think it should look like:

```.st
VLCLibrary>>#macLibraryName
    ^ 'libvlc.dylib'

```

(BTW, I'm interested to support mac)

**Comment by seandenigris** [comment]
Yes, I did 
```smalltalk
VLCLibrary>>#macModuleName 
	^ '/path/to/Pharo.app/Contents/MacOS/Plugins/libvlc.5.dylib'
```
but still got the error.

I also [asked](http://forum.world.st/uFFI-Debugging-External-module-not-found-Error-tp5107642.html) on Pharo Users ML to get more visibility with uFFI gurus.

**Comment by seandenigris** [comment]
Help on the ML from Alistair Grant:

> The same message is returned whether the module itself isn't found, or 
> if one of its dependencies can't be found.
> ...
> On linux you can check dependencies with `ldd file.so`, I don't know 
> what the Mac equivalent is.

Apparently, it's `otool -L libvlc.dylib`, which returns: 
        @rpath/libvlc.dylib (compatibility version 12.0.0, current version 12.0.0) 
        @rpath/libvlccore.dylib (compatibility version 10.0.0, current version 10.0.0) 
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4) 
        /usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0) 

Still investigating...

**Comment by badetitou** [comment]
Hi @seandenigris 

I discovered on Windows that, if we do not load manually libvlccore(.lib), libvlc(.lib) won't work and we get the "module not found" exception

So, one solution is to load libvlccore before.

To test it I have added a libvlccore class (library) in the project and I load the lib using

`VLCLibraryCore uniqueInstance getVersion`

this line fails, but load the library.
Then we can execute
`VLCLibrary uniqueInstance getVersion` without any problem.

Can you try by adding the macLibraryName? 
Do you have any idea how to load correctly a library without this hack?

**Comment by badetitou** [comment]
Hello, 

today I added some methods to pre load the libvlccore library

It has solved the problem on windows
Could you retry on mac ? 

Benoît

**Comment by badetitou** [comment]
Hello,

I finally got a Mac to test the project and found the last error ( it was a problem with environment variable). I personally achieve to run music from my computer with vlc 3.0.8 

I consider the issue close. Feel free to open it again if it does not work in your system

**Comment by seandenigris** [comment]
I confirm it works for me as well! Mojave 10.14.6
